/**
 * Shared topic labels for email templates.
 * Single source of truth — imported by welcome.tsx and preferences-updated.tsx.
 *
 * Must stay in sync with TOPIC_OPTIONS and COMMUNE_OPTIONS in subscribe-form.tsx.
 * When a slug is not found here, emails fall back to displaying the raw slug.
 */
export const topicLabels: Record<string, Record<string, string>> = {
  fr: {
    // Domain topics
    budget: 'Budget',
    mobility: 'Mobilit\u00e9',
    employment: 'Emploi',
    housing: 'Logement',
    climate: 'Climat & \u00c9nergie',
    social: 'Social & Sant\u00e9',
    security: 'S\u00e9curit\u00e9',
    economy: '\u00c9conomie',
    cleanliness: 'Propret\u00e9',
    institutional: 'Institutionnel',
    'urban-planning': 'Urbanisme',
    digital: 'Numérique',
    education: 'Enseignement',
    solutions: 'Sortie de crise',
    engagements: 'Engagements DPR',
    // Communes
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Auderghem',
    'commune-berchem-sainte-agathe': 'Berchem-Sainte-Agathe',
    'commune-bruxelles-ville': 'Bruxelles-Ville',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Forest',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Ixelles',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Molenbeek-Saint-Jean',
    'commune-saint-gilles': 'Saint-Gilles',
    'commune-saint-josse-ten-noode': 'Saint-Josse-ten-Noode',
    'commune-schaerbeek': 'Schaerbeek',
    'commune-uccle': 'Uccle',
    'commune-watermael-boitsfort': 'Watermael-Boitsfort',
    'commune-woluwe-saint-lambert': 'Woluwe-Saint-Lambert',
    'commune-woluwe-saint-pierre': 'Woluwe-Saint-Pierre',
    // Sector topics
    commerce: 'Commerce',
    construction: 'Construction',
    culture: 'Culture',
    environment: 'Environnement',
    'health-social': 'Santé-Social',
    horeca: 'Horeca',
    'housing-sector': 'Logement (secteur)',
    nonprofit: 'Associatif',
    transport: 'Transport',
    // Dossier topics
    dossiers: 'Tous les dossiers',
    'dossier-slrb': 'SLRB',
    'dossier-lez': 'LEZ',
    'dossier-vivaqua': 'Vivaqua',
    'dossier-metro-3': 'Métro 3',
    'dossier-good-move': 'Good Move',
    'dossier-plan-securite': 'Plan Sécurité',
    'dossier-fusion-polices': 'Fusion des zones de police',
    'dossier-seniors': 'Seniors à Bruxelles',
    'dossier-accessibilite-pmr': 'Accessibilité PMR',
    'dossier-data-centers': 'Data Centers & IA',
    'dossier-mobilite-partagee': 'Mobilité partagée',
    'dossier-reforme-administration': "Réforme de l'administration",
    'dossier-assemblees-citoyennes': 'Assemblées citoyennes',
    'dossier-faillites': 'Faillites à Bruxelles',
    // Generic
    communes: 'Toutes les communes',
  },
  nl: {
    budget: 'Budget',
    mobility: 'Mobiliteit',
    employment: 'Werkgelegenheid',
    housing: 'Huisvesting',
    climate: 'Klimaat & Energie',
    social: 'Sociaal & Gezondheid',
    security: 'Veiligheid',
    economy: 'Economie',
    cleanliness: 'Netheid',
    institutional: 'Institutioneel',
    'urban-planning': 'Stedenbouw',
    digital: 'Digitaal',
    education: 'Onderwijs',
    solutions: 'Uitwegen uit de crisis',
    engagements: 'GBV-engagementen',
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Oudergem',
    'commune-berchem-sainte-agathe': 'Sint-Agatha-Berchem',
    'commune-bruxelles-ville': 'Stad Brussel',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Vorst',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Elsene',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Sint-Jans-Molenbeek',
    'commune-saint-gilles': 'Sint-Gillis',
    'commune-saint-josse-ten-noode': 'Sint-Joost-ten-Node',
    'commune-schaerbeek': 'Schaarbeek',
    'commune-uccle': 'Ukkel',
    'commune-watermael-boitsfort': 'Watermaal-Bosvoorde',
    'commune-woluwe-saint-lambert': 'Sint-Lambrechts-Woluwe',
    'commune-woluwe-saint-pierre': 'Sint-Pieters-Woluwe',
    // Sector topics
    commerce: 'Handel',
    construction: 'Bouw',
    culture: 'Cultuur',
    environment: 'Milieu',
    'health-social': 'Gezondheid-Sociaal',
    horeca: 'Horeca',
    'housing-sector': 'Huisvesting (sector)',
    nonprofit: 'Verenigingsleven',
    transport: 'Vervoer',
    // Dossier topics
    dossiers: 'Alle dossiers',
    'dossier-slrb': 'BGHM',
    'dossier-lez': 'LEZ',
    'dossier-vivaqua': 'Vivaqua',
    'dossier-metro-3': 'Metro 3',
    'dossier-good-move': 'Good Move',
    'dossier-plan-securite': 'Veiligheidsplan',
    'dossier-fusion-polices': 'Fusie van politiezones',
    'dossier-seniors': 'Senioren in Brussel',
    'dossier-accessibilite-pmr': 'Toegankelijkheid PBM',
    'dossier-data-centers': 'Datacenters & AI',
    'dossier-mobilite-partagee': 'Gedeelde mobiliteit',
    'dossier-reforme-administration': 'Hervorming van het bestuur',
    'dossier-assemblees-citoyennes': 'Burgerassemblees',
    'dossier-faillites': 'Faillissementen in Brussel',
    // Generic
    communes: 'Alle gemeenten',
  },
  en: {
    budget: 'Budget',
    mobility: 'Mobility',
    employment: 'Employment',
    housing: 'Housing',
    climate: 'Climate & Energy',
    social: 'Social & Health',
    security: 'Security',
    economy: 'Economy',
    cleanliness: 'Cleanliness',
    institutional: 'Institutional',
    'urban-planning': 'Urban Planning',
    digital: 'Digital',
    education: 'Education',
    solutions: 'Exit paths',
    engagements: 'RPD commitments',
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Auderghem',
    'commune-berchem-sainte-agathe': 'Berchem-Sainte-Agathe',
    'commune-bruxelles-ville': 'City of Brussels',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Forest',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Ixelles',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Molenbeek-Saint-Jean',
    'commune-saint-gilles': 'Saint-Gilles',
    'commune-saint-josse-ten-noode': 'Saint-Josse-ten-Noode',
    'commune-schaerbeek': 'Schaerbeek',
    'commune-uccle': 'Uccle',
    'commune-watermael-boitsfort': 'Watermael-Boitsfort',
    'commune-woluwe-saint-lambert': 'Woluwe-Saint-Lambert',
    'commune-woluwe-saint-pierre': 'Woluwe-Saint-Pierre',
    // Sector topics
    commerce: 'Commerce',
    construction: 'Construction',
    culture: 'Culture',
    environment: 'Environment',
    'health-social': 'Health & Social',
    horeca: 'Horeca',
    'housing-sector': 'Housing (sector)',
    nonprofit: 'Nonprofit',
    transport: 'Transport',
    // Dossier topics
    dossiers: 'All dossiers',
    'dossier-slrb': 'SLRB',
    'dossier-lez': 'LEZ',
    'dossier-vivaqua': 'Vivaqua',
    'dossier-metro-3': 'Metro 3',
    'dossier-good-move': 'Good Move',
    'dossier-plan-securite': 'Security Plan',
    'dossier-fusion-polices': 'Police Zone Merger',
    'dossier-seniors': 'Seniors in Brussels',
    'dossier-accessibilite-pmr': 'Accessibility for PRM',
    'dossier-data-centers': 'Data Centers & AI',
    'dossier-mobilite-partagee': 'Shared Mobility',
    'dossier-reforme-administration': 'Administrative Reform',
    'dossier-assemblees-citoyennes': 'Citizen Assemblies',
    'dossier-faillites': 'Bankruptcies in Brussels',
    // Generic
    communes: 'All municipalities',
  },
  de: {
    budget: 'Haushalt',
    mobility: 'Mobilit\u00e4t',
    employment: 'Besch\u00e4ftigung',
    housing: 'Wohnen',
    climate: 'Klima & Energie',
    social: 'Soziales & Gesundheit',
    security: 'Sicherheit',
    economy: 'Wirtschaft',
    cleanliness: 'Sauberkeit',
    institutional: 'Institutionell',
    'urban-planning': 'Städtebau',
    digital: 'Digital',
    education: 'Bildung',
    solutions: 'Auswege aus der Krise',
    engagements: 'RPE-Verpflichtungen',
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Auderghem',
    'commune-berchem-sainte-agathe': 'Berchem-Sainte-Agathe',
    'commune-bruxelles-ville': 'Stadt Br\u00fcssel',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Forest',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Ixelles',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Molenbeek-Saint-Jean',
    'commune-saint-gilles': 'Saint-Gilles',
    'commune-saint-josse-ten-noode': 'Saint-Josse-ten-Noode',
    'commune-schaerbeek': 'Schaerbeek',
    'commune-uccle': 'Uccle',
    'commune-watermael-boitsfort': 'Watermael-Boitsfort',
    'commune-woluwe-saint-lambert': 'Woluwe-Saint-Lambert',
    'commune-woluwe-saint-pierre': 'Woluwe-Saint-Pierre',
    // Sector topics
    commerce: 'Handel',
    construction: 'Bauwesen',
    culture: 'Kultur',
    environment: 'Umwelt',
    'health-social': 'Gesundheit-Soziales',
    horeca: 'Horeca',
    'housing-sector': 'Wohnen (Sektor)',
    nonprofit: 'Vereinswesen',
    transport: 'Verkehr',
    // Dossier topics
    dossiers: 'Alle Dossiers',
    'dossier-slrb': 'SLRB',
    'dossier-lez': 'LEZ',
    'dossier-vivaqua': 'Vivaqua',
    'dossier-metro-3': 'Metro 3',
    'dossier-good-move': 'Good Move',
    'dossier-plan-securite': 'Sicherheitsplan',
    'dossier-fusion-polices': 'Fusion der Polizeizonen',
    'dossier-seniors': 'Senioren in Brüssel',
    'dossier-accessibilite-pmr': 'Barrierefreiheit für PRM',
    'dossier-data-centers': 'Rechenzentren & KI',
    'dossier-mobilite-partagee': 'Geteilte Mobilität',
    'dossier-reforme-administration': 'Verwaltungsreform',
    'dossier-assemblees-citoyennes': 'Bürgerversammlungen',
    'dossier-faillites': 'Insolvenzen in Brüssel',
    // Generic
    communes: 'Alle Gemeinden',
  },
};

/** Get topic labels for a locale, with FR fallback */
export function getTopicLabels(locale: string): Record<string, string> {
  return topicLabels[locale] || topicLabels.fr;
}
