/**
 * Shared topic labels for email templates.
 * Single source of truth — imported by welcome.tsx and preferences-updated.tsx.
 *
 * Must stay in sync with TOPIC_OPTIONS and COMMUNE_OPTIONS in subscribe-form.tsx.
 * When a slug is not found here, emails fall back to displaying the raw slug.
 */
export const topicLabels: Record<string, Record<string, string>> = {
  fr: {
    // Domain topics
    budget: 'Budget',
    mobility: 'Mobilit\u00e9',
    employment: 'Emploi',
    housing: 'Logement',
    climate: 'Climat & \u00c9nergie',
    social: 'Social & Sant\u00e9',
    security: 'S\u00e9curit\u00e9',
    economy: '\u00c9conomie',
    cleanliness: 'Propret\u00e9',
    institutional: 'Institutionnel',
    solutions: 'Sortie de crise',
    engagements: 'Engagements DPR',
    // Communes
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Auderghem',
    'commune-berchem-sainte-agathe': 'Berchem-Sainte-Agathe',
    'commune-bruxelles-ville': 'Bruxelles-Ville',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Forest',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Ixelles',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Molenbeek-Saint-Jean',
    'commune-saint-gilles': 'Saint-Gilles',
    'commune-saint-josse-ten-noode': 'Saint-Josse-ten-Noode',
    'commune-schaerbeek': 'Schaerbeek',
    'commune-uccle': 'Uccle',
    'commune-watermael-boitsfort': 'Watermael-Boitsfort',
    'commune-woluwe-saint-lambert': 'Woluwe-Saint-Lambert',
    'commune-woluwe-saint-pierre': 'Woluwe-Saint-Pierre',
  },
  nl: {
    budget: 'Budget',
    mobility: 'Mobiliteit',
    employment: 'Werkgelegenheid',
    housing: 'Huisvesting',
    climate: 'Klimaat & Energie',
    social: 'Sociaal & Gezondheid',
    security: 'Veiligheid',
    economy: 'Economie',
    cleanliness: 'Netheid',
    institutional: 'Institutioneel',
    solutions: 'Uitwegen uit de crisis',
    engagements: 'GBV-engagementen',
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Oudergem',
    'commune-berchem-sainte-agathe': 'Sint-Agatha-Berchem',
    'commune-bruxelles-ville': 'Stad Brussel',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Vorst',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Elsene',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Sint-Jans-Molenbeek',
    'commune-saint-gilles': 'Sint-Gillis',
    'commune-saint-josse-ten-noode': 'Sint-Joost-ten-Node',
    'commune-schaerbeek': 'Schaarbeek',
    'commune-uccle': 'Ukkel',
    'commune-watermael-boitsfort': 'Watermaal-Bosvoorde',
    'commune-woluwe-saint-lambert': 'Sint-Lambrechts-Woluwe',
    'commune-woluwe-saint-pierre': 'Sint-Pieters-Woluwe',
  },
  en: {
    budget: 'Budget',
    mobility: 'Mobility',
    employment: 'Employment',
    housing: 'Housing',
    climate: 'Climate & Energy',
    social: 'Social & Health',
    security: 'Security',
    economy: 'Economy',
    cleanliness: 'Cleanliness',
    institutional: 'Institutional',
    solutions: 'Exit paths',
    engagements: 'RPD commitments',
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Auderghem',
    'commune-berchem-sainte-agathe': 'Berchem-Sainte-Agathe',
    'commune-bruxelles-ville': 'City of Brussels',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Forest',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Ixelles',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Molenbeek-Saint-Jean',
    'commune-saint-gilles': 'Saint-Gilles',
    'commune-saint-josse-ten-noode': 'Saint-Josse-ten-Noode',
    'commune-schaerbeek': 'Schaerbeek',
    'commune-uccle': 'Uccle',
    'commune-watermael-boitsfort': 'Watermael-Boitsfort',
    'commune-woluwe-saint-lambert': 'Woluwe-Saint-Lambert',
    'commune-woluwe-saint-pierre': 'Woluwe-Saint-Pierre',
  },
  de: {
    budget: 'Haushalt',
    mobility: 'Mobilit\u00e4t',
    employment: 'Besch\u00e4ftigung',
    housing: 'Wohnen',
    climate: 'Klima & Energie',
    social: 'Soziales & Gesundheit',
    security: 'Sicherheit',
    economy: 'Wirtschaft',
    cleanliness: 'Sauberkeit',
    institutional: 'Institutionell',
    solutions: 'Auswege aus der Krise',
    engagements: 'RPE-Verpflichtungen',
    'commune-anderlecht': 'Anderlecht',
    'commune-auderghem': 'Auderghem',
    'commune-berchem-sainte-agathe': 'Berchem-Sainte-Agathe',
    'commune-bruxelles-ville': 'Stadt Br\u00fcssel',
    'commune-etterbeek': 'Etterbeek',
    'commune-evere': 'Evere',
    'commune-forest': 'Forest',
    'commune-ganshoren': 'Ganshoren',
    'commune-ixelles': 'Ixelles',
    'commune-jette': 'Jette',
    'commune-koekelberg': 'Koekelberg',
    'commune-molenbeek-saint-jean': 'Molenbeek-Saint-Jean',
    'commune-saint-gilles': 'Saint-Gilles',
    'commune-saint-josse-ten-noode': 'Saint-Josse-ten-Noode',
    'commune-schaerbeek': 'Schaerbeek',
    'commune-uccle': 'Uccle',
    'commune-watermael-boitsfort': 'Watermael-Boitsfort',
    'commune-woluwe-saint-lambert': 'Woluwe-Saint-Lambert',
    'commune-woluwe-saint-pierre': 'Woluwe-Saint-Pierre',
  },
};

/** Get topic labels for a locale, with FR fallback */
export function getTopicLabels(locale: string): Record<string, string> {
  return topicLabels[locale] || topicLabels.fr;
}
