// SPDX-License-Identifier: LicenseRef-SOURCE-AVAILABLE
// Copyright (c) 2024-2026 Advice That SRL. All rights reserved.

import { NextResponse } from 'next/server';
import { z } from 'zod';
import Anthropic from '@anthropic-ai/sdk';
import { createHash } from 'node:crypto';
import { rateLimit } from '@/lib/rate-limit';
import { buildSystemPrompt } from '@/lib/chat-system-prompt';
import { pushLog } from '@/lib/chat-logs';
import { currentQuestion } from '@/lib/chat-question';
import suggestedAnswersCache from '@/lib/chat-cache/suggested-answers.json';
import { clientIp } from '@/lib/client-ip';
import { sameOriginRefusal } from '@/lib/same-origin';
import { readChatTier, type ChatTier } from '@/lib/chat-access';

export const runtime = 'nodejs';

/**
 * Plafonds d'entree.
 *
 * Ils etaient de 40 messages de 8 000 caracteres, soit l'ordre de grandeur d'un
 * livre court par requete : environ 85 000 jetons non mis en cache, ~0,29 $ la
 * requete, et jusqu'a 170 $ l'heure depuis une seule adresse (audit 21/09).
 * Une question sur une fiche tient tres largement dans ce qui suit.
 */
const MAX_MESSAGES = 12;
const MAX_CONTENT_CHARS = 2000;

const messageSchema = z.object({
  role: z.enum(['user', 'assistant']),
  content: z.string().min(1).max(MAX_CONTENT_CHARS),
});

const bodySchema = z.object({
  messages: z.array(messageSchema).min(1).max(MAX_MESSAGES),
  provider: z.literal('anthropic').default('anthropic'),
  locale: z.string().min(1).max(10).optional(),
  // `tier` N'EST PLUS LU DANS LE CORPS. Il etait envoye par le navigateur, donc
  // choisi par l'appelant : `{"tier":"paid"}` suffisait a obtenir le prompt payant.
  // Le niveau est desormais derive d'un cookie signe cote serveur, pose seulement
  // apres verification du paiement aupres de Stripe (src/lib/chat-access.ts).
});

type Tier = ChatTier;

// Precomputed cache for the 4 suggested questions × 4 locales × 2 tiers.
// Generated by scripts/generate-suggested-answers.ts — regenerate on content
// changes or prompt tweaks via `npm run chat:generate-suggested`.
type SuggestedCache = Record<string, Record<string, Record<string, string>>>;
const SUGGESTED_CACHE = suggestedAnswersCache as SuggestedCache;

function sessionHash(ip: string): string {
  // ECHEC FERME. Le repli etait la chaine litterale 'fallback'. Si la variable
  // sautait lors d'une reconfiguration, la telemetrie continuait de s'ecrire en
  // APPARENCE pseudonymisee, alors que `sha256('fallback'|ip|jour)` se parcourt
  // sur l'espace IPv4 entier en quelques minutes : qui obtenait les journaux
  // retrouvait l'adresse en clair. La politique de confidentialite affirme un
  // « hachage non reversible » : elle aurait ete fausse, en silence.
  // On aligne sur src/lib/token.ts, qui leve deja (audit 21/09).
  const secret = process.env.CHAT_SESSION_SECRET;
  if (!secret) {
    throw new Error(
      'CHAT_SESSION_SECRET is required to pseudonymise chat telemetry. Set it in .env.local.',
    );
  }
  const day = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  return createHash('sha256')
    .update(`${secret}|${ip}|${day}`)
    .digest('hex')
    .slice(0, 12);
}

type UsageContext = {
  provider: 'anthropic';
  locale: string;
  dossierCount: number;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  question: string;
  session: string;
  cached: boolean;
};

function logUsageAsync(ctx: UsageContext): void {
  pushLog('usage', {
    ts: new Date().toISOString(),
    provider: ctx.provider,
    locale: ctx.locale,
    prompt_tokens: ctx.prompt_tokens,
    completion_tokens: ctx.completion_tokens,
    dossier_count: ctx.dossierCount,
    question: ctx.question,
    session: ctx.session,
    cached: ctx.cached,
  });
}

type ErrorLogContext = {
  provider?: string;
  locale?: string;
  session?: string;
  [k: string]: unknown;
};

function logErrorAsync(error: unknown, context: ErrorLogContext): void {
  pushLog('errors', {
    ts: new Date().toISOString(),
    provider: context.provider ?? 'unknown',
    locale: context.locale ?? 'unknown',
    session: context.session ?? 'unknown',
    error: error instanceof Error ? error.message : String(error),
    context,
  });
}

function streamingResponse(
  iter: AsyncIterable<string>,
  ctx: UsageContext,
): Response {
  const encoder = new TextEncoder();
  const readable = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        for await (const chunk of iter) {
          if (chunk) controller.enqueue(encoder.encode(chunk));
        }
        controller.close();
        logUsageAsync(ctx);
      } catch (err) {
        controller.error(err);
      }
    },
  });

  return new Response(readable, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      'X-Accel-Buffering': 'no',
    },
  });
}

async function* anthropicDeltas(
  system: string,
  messages: z.infer<typeof messageSchema>[],
  ctx: UsageContext,
): AsyncIterable<string> {
  const client = new Anthropic();

  try {
    const stream = client.messages.stream({
      model: 'claude-sonnet-4-5',
      max_tokens: 2048,
      temperature: 0.1,
      system: [
        {
          type: 'text',
          text: system,
          cache_control: { type: 'ephemeral' },
        },
      ],
      messages: messages.map((m) => ({ role: m.role, content: m.content })),
    });

    for await (const event of stream) {
      if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
        yield event.delta.text;
      }
    }

    try {
      const final = await stream.finalMessage();
      const input = final.usage.input_tokens ?? 0;
      const cacheCreate = final.usage.cache_creation_input_tokens ?? 0;
      const cacheRead = final.usage.cache_read_input_tokens ?? 0;
      ctx.prompt_tokens = input + cacheCreate + cacheRead;
      ctx.completion_tokens = final.usage.output_tokens ?? null;
    } catch {
      /* usage unavailable — leave nulls */
    }
  } catch (err) {
    logErrorAsync(err, {
      provider: ctx.provider,
      locale: ctx.locale,
      session: ctx.session,
      stage: 'anthropic-stream',
    });
    throw err;
  }
}

/**
 * Fake-stream a cached answer in small chunks so the client sees the familiar
 * "typing" animation. ~30 ms/chunk * ~15 chars ≈ 500 chars/s, similar to
 * Anthropic's streaming speed.
 */
async function* cachedDeltas(text: string): AsyncIterable<string> {
  const CHUNK_SIZE = 15;
  const DELAY_MS = 30;
  for (let i = 0; i < text.length; i += CHUNK_SIZE) {
    yield text.slice(i, i + CHUNK_SIZE);
    await new Promise((resolve) => setTimeout(resolve, DELAY_MS));
  }
}

/**
 * Returns a cached answer if the incoming conversation is exactly one user
 * message whose content matches a precomputed suggested question (exact string
 * match, locale + tier scoped). Falls back to null otherwise.
 */
function lookupCachedAnswer(
  messages: z.infer<typeof messageSchema>[],
  locale: string,
  tier: Tier,
): string | null {
  if (messages.length !== 1) return null;
  const first = messages[0];
  if (first.role !== 'user') return null;
  const question = first.content.trim();
  return SUGGESTED_CACHE[locale]?.[tier]?.[question] ?? null;
}

/** Taille maximale du corps accepte, avant meme de le lire. */
const MAX_BODY_BYTES = 64 * 1024;

/** Quota journalier par adresse, au-dela du plafond par minute. */
const FREE_DAILY_MAX = 30;
const PAID_DAILY_MAX = 300;
const ONE_DAY_MS = 24 * 60 * 60 * 1000;

export async function POST(request: Request) {
  // 1. COUPE-CIRCUIT SERVEUR. `NEXT_PUBLIC_CHATBOT_ENABLED` n'etait teste que
  //    dans le widget : couper le chatbot masquait le bouton et laissait l'API
  //    servie et facturable. Il fallait donc pouvoir couper la depense, pas
  //    seulement l'interface.
  if (process.env.NEXT_PUBLIC_CHATBOT_ENABLED !== 'true') {
    return NextResponse.json({ error: 'Chat disabled' }, { status: 503 });
  }

  // 2. GARDE D'ORIGINE. `Request.json()` ignore le `Content-Type` : un formulaire
  //    en `text/plain` sur un site tiers fabrique un corps JSON valide sans
  //    declencher de preflight CORS. Sans cette garde, n'importe quelle page du
  //    web pouvait faire appeler le modele depuis l'adresse IP de ses visiteurs,
  //    ce qui contourne la limite par adresse par le nombre de victimes.
  //    Le module existait deja et n'etait cable que sur les routes admin.
  const refus = sameOriginRefusal(request.headers);
  if (refus) {
    return NextResponse.json({ error: refus }, { status: 403 });
  }

  // 3. TAILLE DU CORPS. `request.json()` met tout en tampon avant validation :
  //    un corps de plusieurs centaines de Mo tuait le processus.
  const declaredLength = Number(request.headers.get('content-length') ?? '0');
  if (declaredLength > MAX_BODY_BYTES) {
    return NextResponse.json({ error: 'Payload too large' }, { status: 413 });
  }

  const ip = clientIp(request.headers);
  const { allowed } = rateLimit(ip, { max: 10, bucket: 'chat' });
  if (!allowed) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 });
  }

  // 4. NIVEAU D'ACCES DERIVE DU SERVEUR, jamais du corps de la requete.
  const tier = readChatTier(request.headers);

  // 5. QUOTA JOURNALIER. Le quota vivait dans le `localStorage` : le vider
  //    suffisait a le reinitialiser, et un appel direct a l'API l'ignorait.
  const { allowed: sousQuota } = rateLimit(ip, {
    bucket: `chat-jour-${tier}`,
    max: tier === 'paid' ? PAID_DAILY_MAX : FREE_DAILY_MAX,
    windowMs: ONE_DAY_MS,
  });
  if (!sousQuota) {
    return NextResponse.json({ error: 'Daily quota reached', tier }, { status: 429 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const parsed = bodySchema.safeParse(body);
  if (!parsed.success) {
    // Le detail du schema exposait la forme exacte des champs, y compris le nom
    // du champ piege anti-robot que d'autres routes utilisent. Message generique.
    return NextResponse.json({ error: 'Invalid input' }, { status: 400 });
  }

  const { messages } = parsed.data;
  const locale = parsed.data.locale ?? 'fr';

  const session = sessionHash(ip);
  // Le widget renvoie tout l'historique : la question du tour en cours est le
  // dernier message `user`, pas le premier (sinon la télémétrie relogue la
  // question d'ouverture à chaque tour).
  const question = currentQuestion(messages);

  // Fast path: if the conversation is a single suggested question we already
  // precomputed, serve the cached answer without hitting Anthropic. The widget
  // UX stays identical via fake-streaming.
  const cachedAnswer = lookupCachedAnswer(messages, locale, tier);
  if (cachedAnswer) {
    const ctx: UsageContext = {
      provider: 'anthropic',
      locale,
      dossierCount: 0,
      prompt_tokens: null,
      completion_tokens: null,
      question,
      session,
      cached: true,
    };
    return streamingResponse(cachedDeltas(cachedAnswer), ctx);
  }

  // Slow path: build the prompt + call Anthropic.
  const { system, dossierCount } = buildSystemPrompt(tier, locale);

  const ctx: UsageContext = {
    provider: 'anthropic',
    locale,
    dossierCount,
    prompt_tokens: null,
    completion_tokens: null,
    question,
    session,
    cached: false,
  };

  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json(
      { error: 'ANTHROPIC_API_KEY not configured' },
      { status: 500 },
    );
  }
  return streamingResponse(anthropicDeltas(system, messages, ctx), ctx);
}
